name: Workflow for python project

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pylint pytest pytest-cov pytest-pylint
          pip install -rrequirements.txt
          pytest tests --cov=torrentfileQt --cov=tests --pylint --maxfail=2
          coverage report
          coverage xml -o coverage.xml

      - name: Codacy Coverage Report
        uses: codacy/codacy-coverage-reporter-action@v1.1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml

      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@4.0.0

      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
