name: Workflow for python project

on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Code Inspector GitHub action
        uses: codeinspectorio/github-action@v1

      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@4.0.0
